config/routes.rb
Rails.application.routes.draw do
  resources :detalle_ordens
  resources :ordens
  resources :detalle_ordenes
  resources :ordenes
  resources :productos
  resources :clientes
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root :to => 'welcome#index'
  match '/saludo', :to => 'welcome#saludo', :via => [:get]
end

app/models/detalle_orden.rb
class DetalleOrden < ApplicationRecord
  belongs_to :producto
end

app/controllers/detalle_ordens_controller.rb
class DetalleOrdensController < ApplicationController
  before_action :set_detalle_orden, only: [:show, :edit, :update, :destroy]

  # GET /detalle_ordens
  # GET /detalle_ordens.json
  def index
    @detalle_ordens = DetalleOrden.all
  end

  # GET /detalle_ordens/1
  # GET /detalle_ordens/1.json
  def show
  end

  # GET /detalle_ordens/new
  def new
    @detalle_orden = DetalleOrden.new
  end

  # GET /detalle_ordens/1/edit
  def edit
  end

  # POST /detalle_ordens
  # POST /detalle_ordens.json
  def create
    @detalle_orden = DetalleOrden.new(detalle_orden_params)

    respond_to do |format|
      if @detalle_orden.save
        format.html { redirect_to @detalle_orden, notice: 'Detalle orden was successfully created.' }
        format.json { render :show, status: :created, location: @detalle_orden }
      else
        format.html { render :new }
        format.json { render json: @detalle_orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detalle_ordens/1
  # PATCH/PUT /detalle_ordens/1.json
  def update
    respond_to do |format|
      if @detalle_orden.update(detalle_orden_params)
        format.html { redirect_to @detalle_orden, notice: 'Detalle orden was successfully updated.' }
        format.json { render :show, status: :ok, location: @detalle_orden }
      else
        format.html { render :edit }
        format.json { render json: @detalle_orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detalle_ordens/1
  # DELETE /detalle_ordens/1.json
  def destroy
    @detalle_orden.destroy
    respond_to do |format|
      format.html { redirect_to detalle_ordens_url, notice: 'Detalle orden was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detalle_orden
      @detalle_orden = DetalleOrden.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detalle_orden_params
      params.require(:detalle_orden).permit(:producto_id, :cantidad, :precio_venta)
    end
end

app/helpers/detalle_ordens_helper.rb
module DetalleOrdensHelper
end

app/views/detalle_ordens/_form.html.erb
<%= form_with(model: detalle_orden, local: true) do |form| %>
  <% if detalle_orden.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(detalle_orden.errors.count, "error") %> prohibited this detalle_orden from being saved:</h2>

      <ul>
      <% detalle_orden.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :producto_id %>
    <%= form.text_field :producto_id %>
  </div>

  <div class="field">
    <%= form.label :cantidad %>
    <%= form.number_field :cantidad %>
  </div>

  <div class="field">
    <%= form.label :precio_venta %>
    <%= form.text_field :precio_venta %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/detalle_ordens/edit.html.erb
<h1>Editing Detalle Orden</h1>

<%= render 'form', detalle_orden: @detalle_orden %>

<%= link_to 'Mostrar', @detalle_orden %> |
<%= link_to 'Regresar', detalle_ordens_path %>

app/views/detalle_ordens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Detalle Ordenes</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Producto</th>
      <th scope="col">Cantidad</th>
      <th scope="col">Precio venta</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @detalle_ordens.each do |detalle_orden| %>
      <tr>
        <th scope="row"><%= detalle_orden.id %></td>
        <td><%= detalle_orden.producto.nombre_producto %></td>
        <td><%= detalle_orden.cantidad %></td>
        <td>$<%= detalle_orden.precio_venta %></td>
        <td><%= link_to 'Mostrar', detalle_orden %></td>
        <td><%= link_to 'Editar', edit_detalle_orden_path(detalle_orden) %></td>
        <td><%= link_to 'Eliminar', detalle_orden, method: :delete, data: { confirm: '¿Seguro que desea eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Añadir Detalle Orden', new_detalle_orden_path %>

app/views/detalle_ordens/new.html.erb
<h1>New Detalle Orden</h1>

<%= render 'form', detalle_orden: @detalle_orden %>

<%= link_to 'Regresar', detalle_ordens_path %>

app/views/detalle_ordens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Producto:</strong>
  <%= @detalle_orden.producto.nombre_producto %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @detalle_orden.cantidad %>
</p>

<p>
  <strong>Precio venta:</strong>
  <%= @detalle_orden.precio_venta %>
</p>

<%= link_to 'Editar', edit_detalle_orden_path(@detalle_orden) %> |
<%= link_to 'Regresar', detalle_ordens_path %>